printers:
  MK4:
    name: "Prusa MK4"
    # nozzles: ["0.4mm"]
    filaments: ["PLA_ROSA", "PETG_ROSA", "TPU_ROSA"]
    profiles: ["DRAFT", "DETAIL", "SPEED"]
    apply_filament_settings: True

  XL:
    name: "Prusa XL"
    # nozzles: ["1: 0.4mm", "2: 0.4mm", "3: 0.4mm", "4: 0.4mm", "5: 0.4mm"]
    filaments: ["PLA_ROSA", "PETG_ROSA", "TPU_ROSA"]
    profiles: ["SPEED", "STRUCTURAL"]
    apply_filament_settings: False

  CR10:
    name: "Creality CR10"
    # nozzles: ["0.6mm"]
    filaments: ["PLA_ROSA"]
    profiles: ["SUPERDRAFT"]
    apply_filament_settings: True

fill_pattern:
  rectilinear: "Rectiligne"
  honeycomb: "Nid d'abeille"
  gyroid: "Gyroide"
  adaptivecubic: "Cubique Adaptatif"

fill_density: ["5%", "10%", "20%", "40%", "60%"]

prusa_path: "C:/Program Files/Prusa3D/PrusaSlicer/prusa-slicer.exe"